#!/bin/sh

set -e

case $FGC_NETWORK in
  local|regtest)
    SELECT_NETWORK=-regtest
    ;;
  test|testnet)
    SELECT_NETWORK=-testnet
    ;;
  main|mainnet)
    SELECT_NETWORK=
    ;;
  *)
    echo "Unknown network: $FGC_NETWORK"
    exit 1
esac

mkdir -p $FGC_DATADIR

exec fantasygoldd ${SELECT_NETWORK} \
  -rpcbind=0.0.0.0:57810 -rpcallowip=172.17.0.0/16 \
  -datadir=$FGC_DATADIR \
  -logevents \
  -rpcuser=$FGC_RPC_USER -rpcpassword=$FGC_RPC_PASS \
  -printtoconsole
